[toolchain]
package_manager = "npm"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
wager_escrow = "JCRT7U9RoxcQ7xt5PkZ3EsrPkDswGQRfcKkc2qB9cx4m"

[programs.devnet]
wager_escrow = "JCRT7U9RoxcQ7xt5PkZ3EsrPkDswGQRfcKkc2qB9cx4m"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/wager-escrow.js"
